### PR TITLE
feat: Table component

### PR DESCRIPTION
**Pull request by callinmullaney**
**Summary**
- Adds a boilerplate table component to compound.

This PR fixes/implements the following **bugs/features**
- Rewrites the table component currently bundled with compound to use BEM (no longer just placeholder markup)

Explain the **motivation** for making this change. What existing problem does the pull request solve?
- Current table implementation is just markup placeholder and isn't mean to actually integrate with an installed platform

**Documentation Update (required)**
- None

**How to review this PR**
- [x] checkout branch and run `npm install` then `npm run storybook`
- [x] Go to `Atoms/Tables` and confirm you can see a table with odd/even shading. 
- [x] Inspect the markup and confirm it's using `bem` class structure
- [x] Review the twig and styles and verify they are a good starting point for future projects and arent too opinionated.

### CODE REVIEW

**Review by ryanhagerty — COMMENTED** [review]
Looks like a great starting point. Great work including the optional `colgroup` and `tfoot` in the `twig` file.

One thing I think would be great: since the table is already styled to alternate colors for rows, I think we should have the `border` color be updated/easily overridden as well. Screenshot below:

Screen Shot 2021-12-23 at 8 21 09 AM

**Comment by ryanhagerty** [comment]
This is more of an open question:

How do we feel about making a follow-up ticket to make our tables responsive by default?

It's such a common feature request that takes a chunk of time, but my only hesitation is that it drifts into the field of 'too opinionated'. If we think it's too much, we could have an option for a 'standard (basic) table' and a 'responsive table' that users could pick from when starting up the CLI.

**Comment by callinmullaney** [comment]
@ryanhagerty I refactored this a bit and made the following changes:
1. Utilize `add_attributes` twig function on table and cells. This allows the platform (drupal) to inject whatever attributes it needs like `no_striping` or `sticky`.
2. Fixed the border colors mentioned in your comment above so striped rows maintain the borders between cells.
3. Add an example `data-cell-highlight` to a column of cells and updated styles. This is strictly to demonstrate how to add attributes to individual cells within the same yml file.

As for the responsive table comment. I definitely agree with your assessment that this is a typical time consuming request. However, because the `overflow:scroll` method is less than ideal and the restacking method is more opinionated, I decided to leave that feature out of this PR for now. I think once we develop our 4K specific component library that is based on Compound we can explore this request further.

**Comment by callinmullaney** [comment]
@ModulesUnraveled I welcome your review of this PR as well :smile:

**Review by ryanhagerty — APPROVED** [review]
LGTM 🌯

**Pull request merged**
